// deep-research-agent/web/src/components/ParticleBg.tsx
import { useEffect, useState, Suspense, lazy } from 'react'

// tsparticles has complex ESM types — lazy-load to avoid build-time issues
const Particles = lazy(() => import('@tsparticles/react').then(m => ({ default: m.default || (m as any).Particles })))

export default function ParticleBg() {
  const [mounted, setMounted] = useState(false)
  useEffect(() => { setMounted(true) }, [])

  if (!mounted) return null

  return (
    <Suspense fallback={null}>
      <Particles
        style={{ position: 'fixed', top: 0, left: 0, zIndex: 0 } as any}
        options={{
          fpsLimit: 60,
          particles: {
            number: { value: 40, density: { enable: true } },
            color: { value: ['#00d4ff', '#7b2fff', '#64748b'] },
            opacity: { value: 0.15 },
            size: { value: { min: 1, max: 3 } },
            move: { enable: true, speed: 0.6 },
            links: { enable: true, color: '#334155', opacity: 0.1, distance: 150 },
          },
          interactivity: {
            events: { onHover: { enable: true, mode: 'grab' } },
            modes: { grab: { distance: 180, links: { opacity: 0.3 } } },
          },
        }}
      />
    </Suspense>
  )
}

// deep-research-agent/web/src/components/ParticleBg.vue
<template>
  <VueParticles
    id="tsparticles"
    class="particle-container"
    :options="particleOptions"
  />
</template>

<script setup>
const particleOptions = {
  fullScreen: { enable: false },
  fpsLimit: 60,
  particles: {
    color: { value: '#00f0ff' },
    links: {
      color: '#00f0ff',
      distance: 150,
      enable: true,
      opacity: 0.15,
      width: 1
    },
    move: {
      enable: true,
      speed: 0.6,
      direction: 'none',
      random: true,
      straight: false,
      outModes: { default: 'bounce' }
    },
    number: {
      density: { enable: true },
      value: 60
    },
    opacity: {
      value: { min: 0.1, max: 0.4 },
      animation: {
        enable: true,
        speed: 0.5,
        minimumValue: 0.1
      }
    },
    shape: { type: 'circle' },
    size: {
      value: { min: 1, max: 2.5 }
    }
  },
  interactivity: {
    events: {
      onHover: {
        enable: true,
        mode: 'grab'
      }
    },
    modes: {
      grab: {
        distance: 140,
        links: {
          opacity: 0.3
        }
      }
    }
  },
  detectRetina: true
}
</script>

<style scoped>
.particle-container {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 0;
  pointer-events: none;
}

.particle-container :deep(canvas) {
  pointer-events: auto !important;
}
</style>
